cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

pages:
  image: node:latest
  stage: deploy
  script:
    - yarn install
    - yarn build
    - cp dist/* public
  artifacts:
    paths:
      - public
  only:
    - master
