cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

pages:
  image: node:latest
  stage: deploy
  script:
    - yarn install
    - yarn build
    - mv dist public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - master
