cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

pages:
  image: node:latest
  stage: deploy
  script:
    - yarn install
    - yarn build
    - mv dist public
    - cd public
    - rm index.html
    - add dist/index.html
    - add dist/main.js
  artifacts:
    paths:
      - public
  only:
    - master
